//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mixer_control_globalver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mixer_control_globalver.Properties.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation Process.
        /// </summary>
        public static string btnAutomationTab_Text {
            get {
                return ResourceManager.GetString("btnAutomationTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check formula process.
        /// </summary>
        public static string btnCheckProcess {
            get {
                return ResourceManager.GetString("btnCheckProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Selection.
        /// </summary>
        public static string btnChooseSpecTab_Text {
            get {
                return ResourceManager.GetString("btnChooseSpecTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to automation process.
        /// </summary>
        public static string btnContinueAutomation_Text {
            get {
                return ResourceManager.GetString("btnContinueAutomation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW (Clockwise).
        /// </summary>
        public static string btnNormalRoll_Text {
            get {
                return ResourceManager.GetString("btnNormalRoll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Stop.
        /// </summary>
        public static string btnResetRoll_Text {
            get {
                return ResourceManager.GetString("btnResetRoll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCW (Counterclockwise).
        /// </summary>
        public static string btnReverseRoll_Text {
            get {
                return ResourceManager.GetString("btnReverseRoll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the current step.
        /// </summary>
        public static string btnStartAutomation_Text {
            get {
                return ResourceManager.GetString("btnStartAutomation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Supply Machine Test.
        /// </summary>
        public static string btnTestOilFeed {
            get {
                return ResourceManager.GetString("btnTestOilFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Scan.
        /// </summary>
        public static string btnWeightTab_Text {
            get {
                return ResourceManager.GetString("btnWeightTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initiate connection to PLC.
        /// </summary>
        public static string Error_CannotInitPLC {
            get {
                return ResourceManager.GetString("Error_CannotInitPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read this formula file data.
        ///.
        /// </summary>
        public static string Error_CannotLoadExcelFile {
            get {
                return ResourceManager.GetString("Error_CannotLoadExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read directory data containing formulas.
        ///How to fix:
        ///- Check if the directory being deleted or moved to another place? 
        ///- Check the internet connection in the lower right corner of the screen.
        ///- If the internet connection is normal, the server may have lost connection. Please contact the IT department..
        /// </summary>
        public static string Error_CannotLoadFormulaList {
            get {
                return ResourceManager.GetString("Error_CannotLoadFormulaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QR code just scan is not in the right format. Please check again..
        /// </summary>
        public static string Error_CanNotRecognizeQR {
            get {
                return ResourceManager.GetString("Error_CanNotRecognizeQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open Excel file. .
        /// </summary>
        public static string Error_ReadFile {
            get {
                return ResourceManager.GetString("Error_ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Name.
        /// </summary>
        public static string FormulaListHeaderText {
            get {
                return ResourceManager.GetString("FormulaListHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned material name:.
        /// </summary>
        public static string Label_CurrentScannedMaterialName {
            get {
                return ResourceManager.GetString("Label_CurrentScannedMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string Label_CurrentSpeed {
            get {
                return ResourceManager.GetString("Label_CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        public static string Label_CurrentTemperature {
            get {
                return ResourceManager.GetString("Label_CurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select formula directory.
        /// </summary>
        public static string Label_FormulaDirectorySetup {
            get {
                return ResourceManager.GetString("Label_FormulaDirectorySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string Label_PasswordConfirm {
            get {
                return ResourceManager.GetString("Label_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned materials / total materials.
        /// </summary>
        public static string Label_ScannedMaterialAmount {
            get {
                return ResourceManager.GetString("Label_ScannedMaterialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned material code.
        /// </summary>
        public static string Label_ScannedMaterialCode {
            get {
                return ResourceManager.GetString("Label_ScannedMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Name.
        /// </summary>
        public static string Label_ScannedMaterialFormulaName {
            get {
                return ResourceManager.GetString("Label_ScannedMaterialFormulaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material lists.
        /// </summary>
        public static string Label_ScannedMaterialList {
            get {
                return ResourceManager.GetString("Label_ScannedMaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected formula :.
        /// </summary>
        public static string Label_SelectedFormula {
            get {
                return ResourceManager.GetString("Label_SelectedFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (rpm).
        /// </summary>
        public static string Label_SpeedUnit {
            get {
                return ResourceManager.GetString("Label_SpeedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Celsius).
        /// </summary>
        public static string Label_TemperatureUnit {
            get {
                return ResourceManager.GetString("Label_TemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation mode is off. Cannot start the process..
        /// </summary>
        public static string Message_AutomationIsOff {
            get {
                return ResourceManager.GetString("Message_AutomationIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can NOT connect to oil supply machine..
        /// </summary>
        public static string Message_CanNOTConnectToOilSupply {
            get {
                return ResourceManager.GetString("Message_CanNOTConnectToOilSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the current process? 
        ///Please note that all material have been put in the mixer before hit start!.
        /// </summary>
        public static string Message_ConfirmStart {
            get {
                return ResourceManager.GetString("Message_ConfirmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application ? .
        /// </summary>
        public static string Message_ExitApplication {
            get {
                return ResourceManager.GetString("Message_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current automation formula is finished. .
        /// </summary>
        public static string Message_FormulaFinished {
            get {
                return ResourceManager.GetString("Message_FormulaFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart process is required to apply new language. Do you want to close the application ?.
        /// </summary>
        public static string Message_LanguageChange {
            get {
                return ResourceManager.GetString("Message_LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a formula first!.
        /// </summary>
        public static string Message_NotChooseFormulaAlert {
            get {
                return ResourceManager.GetString("Message_NotChooseFormulaAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil supply mode not being turned on yet..
        /// </summary>
        public static string Message_NotEnableOilSupplyFunctionYet {
            get {
                return ResourceManager.GetString("Message_NotEnableOilSupplyFunctionYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input all required setting first!.
        /// </summary>
        public static string Message_NotInputAllBaseSetting {
            get {
                return ResourceManager.GetString("Message_NotInputAllBaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm all materials first!.
        /// </summary>
        public static string Message_NotScanAllMaterial {
            get {
                return ResourceManager.GetString("Message_NotScanAllMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the PDF_417 code on the SOP file first..
        /// </summary>
        public static string Message_NotScanPDF417 {
            get {
                return ResourceManager.GetString("Message_NotScanPDF417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil supply machine is running..
        /// </summary>
        public static string Message_OilSupplyIsRunning {
            get {
                return ResourceManager.GetString("Message_OilSupplyIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil feeder checked!\r\nTime:\r\n.
        /// </summary>
        public static string Message_OilTested {
            get {
                return ResourceManager.GetString("Message_OilTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SOP PDF_417 code you just scanned is not match with the selected automation formula please check again..
        /// </summary>
        public static string Message_PDF417NotMatch {
            get {
                return ResourceManager.GetString("Message_PDF417NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanned SOP code matches the selected formula. Please scan the material codes included in the SOP..
        /// </summary>
        public static string Message_PDF417Scanned {
            get {
                return ResourceManager.GetString("Message_PDF417Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is finished. Press &quot;OK&quot; to open mixer lid and &quot;Cancel&quot; to keep the mixer lid close..
        /// </summary>
        public static string Message_ProcessFinished {
            get {
                return ResourceManager.GetString("Message_ProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing please wait a moment ....
        /// </summary>
        public static string Message_Processing {
            get {
                return ResourceManager.GetString("Message_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing a new formula will cause current and previous data to be lost and reset. Continue ?.
        /// </summary>
        public static string Message_ResetSpecTab {
            get {
                return ResourceManager.GetString("Message_ResetSpecTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to the next process..
        /// </summary>
        public static string Message_SkipProcess {
            get {
                return ResourceManager.GetString("Message_SkipProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring oil mass information ....
        /// </summary>
        public static string Message_TransferingOilMass {
            get {
                return ResourceManager.GetString("Message_TransferingOilMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for sensor data indicate the mixer is in the right position..
        /// </summary>
        public static string Message_WaitForSensorData {
            get {
                return ResourceManager.GetString("Message_WaitForSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxTitle_Error {
            get {
                return ResourceManager.GetString("MessageBoxTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageBoxTitle_Information {
            get {
                return ResourceManager.GetString("MessageBoxTitle_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxTitle_Warning {
            get {
                return ResourceManager.GetString("MessageBoxTitle_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft YaHei UI.
        /// </summary>
        public static string Text_Font {
            get {
                return ResourceManager.GetString("Text_Font", resourceCulture);
            }
        }
    }
}
